///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package clases;
//
//
//import java.io.IOException;
//
//import javafx.application.Application;
//import javafx.event.ActionEvent;
//import javafx.fxml.FXMLLoader;
//import javafx.scene.Parent;
//import javafx.scene.Scene;
//import javafx.stage.Stage;
//
//public class Main extends Application {
//
//    public static Object handleButtonAction;
//
//	@Override
//    public void start(Stage stage) throws Exception {
////        String javaVersion = System.getProperty("java.version");
////        String javafxVersion = System.getProperty("javafx.version");
////        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
////        Scene scene = new Scene(new StackPane(l), 640, 480);
////        stage.setScene(scene);
////        stage.show();
////    	
//    	Parent root = FXMLLoader.load(getClass().getResource("BasicFxml.fxml"));
//        Scene scene = new Scene(root);
//        stage.setScene(scene);
//        stage.show();
//    }
////    public void start(Stage stage) throws Exception {
////        Parent root = FXMLLoader.load(getClass().getResource("BasicFxml.fxml"));
////        Scene scene = new Scene(root);
////        stage.setScene(scene);
////        stage.show();
////    }
//    public void handleButtonAction(ActionEvent event) {
//        
//	    try {
//	      Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("BasicFxml2.fxml"));
//	      Stage stage = new Stage();
//	      stage.setTitle("My New Stage Title");
//	      stage.setScene(new Scene(root, 450, 450));
//	      stage.show();
//	      // Hide this current window (if this is what you want)
//	     
//	    }
//	    catch (IOException e) {
//	      e.printStackTrace();
//	    }
//	    
//	}
//    public void handleButtonAction1(ActionEvent event) {
//    	
//    }
//
//    public static void main(String[] args) {
//        launch();
//    }
//}
package gui.viewsandcontrollers.main;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class Main extends Application {

    public static Object nuevo;

	@Override
    public void start(Stage stage) throws Exception {
		
		Parent root = FXMLLoader.load(getClass().getResource("biblioteca.fxml"));
        Scene scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }
//	public void nuevo(ActionEvent event) throws IOException {
//      
////	    try {
////	      Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("libroform.fxml"));
////	      Stage stage = new Stage();
////	      stage.setTitle("My New Stage Title");
////	      stage.setScene(new Scene(root, 450, 450));
////	      stage.show();
////	      // Hide this current window (if this is what you want)
//		
////	    }
////	    catch (IOException e) {
////	      e.printStackTrace();
////	    }
//	}
	public static void main(String[] args) {
        launch();
    }
}